workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-32
  replicaCount: 1
  containerSpec:
    imageUri: us-central1-docker.pkg.dev/birdclef-490003/birdclef-repo/perch-extractor:test-v2
    command: ["python3", "src/audio/select_fusion_peaks_fast.py"]
    args:
    - --workers=30
    - --gcs_bucket=birdclef-2026-data-birdclef-490003
    env:
    - name: GCS_BUCKET
      value: "birdclef-2026-data-birdclef-490003"
    - name: PYTHONPATH
      value: "."
